name: Cloudflare WARP Connect

on: [push]

jobs:
  setup-cloudflare-warp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cloudflare WARP
        uses: Boostport/setup-cloudflare-warp@v1
        with:
          organization: theinfinox.cloudflareaccess.com
          auth_client_id: ${{ secrets.CLOUDFLARE_AUTH_CLIENT_ID }}
          auth_client_secret: ${{ secrets.CLOUDFLARE_AUTH_CLIENT_SECRET }}

      - name: Test access to secured resource
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.RPI_SSH_KEY }}" | base64 --decode > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to Raspberry Pi
        run: |
          ssh-keyscan -H 192.168.29.175 >> ~/.ssh/known_hosts
          ssh pi@192.168.29.175 'mkdir -p ~/pi/alchemy-docker/alchemy'
          rsync -avz --delete -vv ~/pi/alchemy pi@192.168.29.175:~/pi/alchemy-docker/alchemy
